//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Numbers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Numbers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumbersApi.Resources.Numbers", typeof(Numbers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be specified. .
        /// </summary>
        public static string ArgumentNullErrorMessage {
            get {
                return ResourceManager.GetString("ArgumentNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-gb.
        /// </summary>
        public static string DefaultCulture {
            get {
                return ResourceManager.GetString("DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options must be specified in the request body..
        /// </summary>
        public static string EmptyContentErrorMessage {
            get {
                return ResourceManager.GetString("EmptyContentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-gb.
        /// </summary>
        public static string EnabledLanguagesArray {
            get {
                return ResourceManager.GetString("EnabledLanguagesArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an integer to get the equivalent in British English words..
        /// </summary>
        public static string IntroMessage {
            get {
                return ResourceManager.GetString("IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not valid..
        /// </summary>
        public static string InvalidNumberErrorMessage {
            get {
                return ResourceManager.GetString("InvalidNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer must be between @ and #..
        /// </summary>
        public static string NumberOverflowErrorMessage {
            get {
                return ResourceManager.GetString("NumberOverflowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        public static string SettingsArraySeparator {
            get {
                return ResourceManager.GetString("SettingsArraySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test;123;true;-2123;.
        /// </summary>
        public static string testUtilitiesGetSettingsList {
            get {
                return ResourceManager.GetString("testUtilitiesGetSettingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture is currently not supported..
        /// </summary>
        public static string UnsupportedCultureMessage {
            get {
                return ResourceManager.GetString("UnsupportedCultureMessage", resourceCulture);
            }
        }
    }
}
